config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :home do
        collection do
          post :search
        end
      end
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    authenticated :user do
      root to: 'pages#index', as: :authenticated_root
      get '/users/sign_out', to: 'devise/sessions#destroy'

      resources :members, only: %i[index new create edit update] do
        collection do
          get :regions
          get :districts
          get :groups
          get :units
          get :advance
          get :states
          get :provinces
          post :verificate
        end
      end

      get '/members/grupo'
      get '/members/group_youth'
      get '/members/dualidad'
      get '/members/institucional'
      get '/members/legal_tutor'
      post '/members/grupo_submit'
      post '/members/group_youth_submit'
      post '/members/dualidad_submit'
      post '/members/institucional_submit'
      post '/members/legal_tutor_submit'
      post '/members/verificate'

      namespace :users do
        resources :amounts
        resources :profiles, only: %i[index]
        resources :resets, only: %i[update] do
          collection do
            get :group
            get :district
            get :region
          end
        end
        resources :reports do
          collection do
            get :payments
            get :members
            get :tutors_legals
            get :numerical_cutoff
            get :my_group
            get :my_district
            get :my_region
            get :reports_by_payments, format: :xlsx
            get :reports_by_members, format: :xlsx
            get :reports_by_tutors_legals, format: :xlsx
            get :reports_by_numerical_cutoff, format: :xlsx
            get :reports_by_my_group, format: :xlsx
            get :reports_by_my_district, format: :xlsx
            get :reports_by_my_region, format: :xlsx
          end
        end
        resources :payments, only: %i[index new create show destroy] do
          collection do
            get :checkings
            post :swap
          end
        end
        resources :roles, except: [:show]
        resources :vaccines, except: [:show]
        resources :allergies, excep: [:show]
        resources :diseases, excep: [:show]
        resources :histories, excep: [:show]
        resources :handicaps, excep: [:show]
        resources :intolerances, excep: [:show]
        resources :medical_files, only: %i[new edit create update]
        resources :assignments, only: %i[index] do
          collection do
            post :assignment
          end
        end
      end
    end

    unauthenticated :user do
      root to: 'users/sessions#new', as: :unauthenticated_root
    end

    get 'static_pages/no_permissions', to: 'static_pages#no_permissions', as: 'static_pages_no_permissions'
  end
end

app/controllers/users/allergies_controller.rb
class Users::AllergiesController < ApplicationController
  include VerificateControllerConcern

  before_action :validate_payment
  before_action :set_users_allergy, only: %i[edit update destroy]
  before_action :authorize_users_allergies

  def index
    @allergies = Allergy.all
  end

  def new
    @users_allergy = Allergy.new
  end

  def edit; end

  def create
    @users_allergy = Allergy.new(users_allergy_params)

    return redirect_to users_allergies_url, notice: t('.created') if @users_allergy.save

    render :new, status: :unprocessable_entity
  end

  def update
    return redirect_to users_allergies_url, notice: t('.updated') if @users_allergy.update(users_allergy_params)

    render :edit, status: :unprocessable_entity
  end

  def destroy
    @users_allergy.destroy
    redirect_to users_allergies_url, notice: t('.destroyed')
  end

  private

  def set_users_allergy
    @users_allergy = Allergy.find(params[:id])
  end

  def users_allergy_params
    params.require(:allergy).permit(:allergies_name, :allergies_status)
  end

  def authorize_users_allergies
    authorize %i[users allergies]
  end
end

app/controllers/users/amounts_controller.rb
class Users::AmountsController < ApplicationController
  include VerificateControllerConcern

  before_action :validate_payment
  before_action :authorize_users_amount
  before_action :set_users_amount, only: %i[ show edit update destroy ]

  def index
    @users_amounts = Amount.all
  end

  def show; end

  def new
    @users_amount = Amount.new
  end

  def edit; end

  def create
    @users_amount = Amount.new(users_amount_params)
    return redirect_to users_amount_url(@users_amount), notice: 'Monto creado con exito.' if @users_amount.save

    render :new, status: :unprocessable_entity
  end

  def update
    return redirect_to users_amount_url(@users_amount), notice: 'Monto actualizado correctamente.' if @users_amount.update(users_amount_params)

    render :edit, status: :unprocessable_entity
  end

  def destroy
    @users_amount.destroy
    redirect_to users_amounts_url, notice: 'Monto eliminado.'
  end

  private

  def set_users_amount
    @users_amount = Amount.find(params[:id])
  end

  def authorize_users_amount
    authorize [:users, :amounts]
  end

  def users_amount_params
    params.require(:amount).permit(:amount_name, :amount_usd, :amount_exchange, :amount_type, :amount_status)
  end
end

app/controllers/users/assignments_controller.rb
class Users::AssignmentsController < ApplicationController
  include VerificateControllerConcern

  before_action :validate_payment
  before_action :authorize_users_assignments, only: [:index, :assignment]

  def index
    @list_roles = Role.all
  end

  def assignment
    user = User.find_by_email(params[:email])
    rol = Role.find_by_id(params[:rol])

    unless user && rol
      redirect_to users_assignments_path, notice: 'No se encontró el email o el rol'
      return
    end

    user.update(role_id: rol.id)
    redirect_to users_assignments_path, notice: 'Asignado con éxito'
  end

  private

  def authorize_users_assignments
    authorize [:users, :assignments]
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  include VerificateControllerConcern
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    # Realiza la autenticación, verifica la autenticación
    sign_in(resource_name, resource)

    if signed_in?(resource_name)
      verificate(resource)
    else
      super
    end
  end
end

app/controllers/users/diseases_controller.rb
class Users::DiseasesController < ApplicationController
  include VerificateControllerConcern

  before_action :validate_payment
  before_action :set_users_disease, only: %i[edit update destroy]
  before_action :authorize_users_diseases

  def index
    @diseases = Disease.all
  end

  def new
    @users_disease = Disease.new
  end

  def edit; end

  def create
    @users_disease = Disease.new(users_disease_params)

    return redirect_to users_diseases_url, notice: t('.created') if @users_disease.save

    render :new, status: :unprocessable_entity
  end

  def update
    return redirect_to users_diseases_url, notice: t('.updated') if @users_disease.update(users_disease_params)

    render :edit, status: :unprocessable_entity
  end

  def destroy
    @users_disease.destroy
    redirect_to users_diseases_url, notice: t('.destroyed')
  end

  private

  def set_users_disease
    @users_disease = Disease.find(params[:id])
  end

  def users_disease_params
    params.require(:disease).permit(:diseases_name, :diseases_status)
  end

  def authorize_users_diseases
    authorize %i[users diseases]
  end
end

app/controllers/users/handicaps_controller.rb
class Users::HandicapsController < ApplicationController
  include VerificateControllerConcern

  before_action :validate_payment
  before_action :set_users_handicap, only: %i[edit update destroy]
  before_action :authorize_users_handicaps

  def index
    @handicaps = Handicap.all
  end

  def new
    @users_handicap = Handicap.new
  end

  def edit; end

  def create
    @users_handicap = Handicap.new(users_handicap_params)

    return redirect_to users_handicaps_url, notice: t('.created') if @users_handicap.save

    render :new, status: :unprocessable_entity
  end

  def update
    return redirect_to users_handicaps_url, notice: t('.updated') if @users_handicap.update(users_handicap_params)

    render :edit, status: :unprocessable_entity
  end

  def destroy
    @users_handicap.destroy
    redirect_to users_handicaps_url, notice: t('.destroyed')
  end

  private

  def set_users_handicap
    @users_handicap = Handicap.find(params[:id])
  end

  def users_handicap_params
    params.require(:handicap).permit(:handicaps_name, :handicaps_status)
  end

  def authorize_users_handicaps
    authorize %i[users handicaps]
  end
end

app/controllers/users/histories_controller.rb
class Users::HistoriesController < ApplicationController
  include VerificateControllerConcern

  before_action :validate_payment
  before_action :set_users_history, only: %i[edit update destroy]
  before_action :authorize_users_histories

  def index
    @histories = History.all
  end

  def new
    @users_history = History.new
  end

  def edit; end

  def create
    @users_history = History.new(users_history_params)

    return redirect_to users_histories_url, notice: t('.created') if @users_history.save

    render :new, status: :unprocessable_entity
  end

  def update
    return redirect_to users_histories_url, notice: t('.updated') if @users_history.update(users_history_params)

    render :edit, status: :unprocessable_entity
  end

  def destroy
    @users_history.destroy
    redirect_to users_histories_url, notice: t('.destroyed')
  end

  private

  def set_users_history
    @users_history = History.find(params[:id])
  end

  def users_history_params
    params.require(:history).permit(:histories_name, :histories_status)
  end

  def authorize_users_histories
    authorize %i[users histories]
  end
end

app/controllers/users/intolerances_controller.rb
class Users::IntolerancesController < ApplicationController
  include VerificateControllerConcern

  before_action :validate_payment
  before_action :set_users_intolerance, only: %i[edit update destroy]
  before_action :authorize_users_intolerances

  def index
    @intolerances = Intolerance.all
  end

  def new
    @users_intolerance = Intolerance.new
  end

  def edit; end

  def create
    @users_intolerance = Intolerance.new(users_intolerance_params)

    return redirect_to users_intolerances_url, notice: t('.created') if @users_intolerance.save

    render :new, status: :unprocessable_entity
  end

  def update
    return redirect_to users_intolerances_url, notice: t('.updated') if @users_intolerance.update(users_intolerance_params)

    render :edit, status: :unprocessable_entity
  end

  def destroy
    @users_intolerance.destroy
    redirect_to users_intolerances_url, notice: t('.destroyed')
  end

  private

  def set_users_intolerance
    @users_intolerance = Intolerance.find(params[:id])
  end

  def users_intolerance_params
    params.require(:intolerance).permit(:intolerances_name, :intolerances_status)
  end

  def authorize_users_intolerances
    authorize %i[users intolerances]
  end
end

# FRANCISCO JAVIER VALLECILLO
# 900535025
# sociasysocios.es@greenpas.org

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  include VerificateControllerConcern

  before_action :validate_payment

  def index
    authorize [:users, :profiles]
    @member = current_user.member
    @medical_files = MedicalFile.find_by_member_id(@member.id)
    @vaccines_member = current_user.member.vaccine_members.active
    @allergies_member = current_user.member.allergy_members.active
    @diseases_member = current_user.member.disease_members.active
    @histories_member = current_user.member.history_members.active
    @handicaps_member = current_user.member.handicap_members.active
    @intolerances_member = current_user.member.intolerance_members.active
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # before_action :set_params_user, only: [:create]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   # super
  #   @user = User.new(set_params_user)
  #   byebug
  #   if @user.valid?
  #     self.resource = warden.authenticate!(auth_options)
  #     if resource.confirmed?
  #       sign_in(resource_name, resource)
  #       redirect_to root_path
  #     else
  #       redirect_to new_user_confirmation_path
  #     end
  #   else
  #     super
  #   end
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   # super(resource)
  #   if resource.completeness < 100
  #     edit_member_path(resource.member) if resource.member.present?
  #     members_path unless resource.member.present?
  #   else
  #     root_path
  #   end
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    role = Role.find_by_rol_name("User")
    resource.update(role:)
    super(resource)
  end
  # def set_params_user
  #   params.require(:user).permit(:email, :password, :password_confirmation)
  # end
end

app/controllers/users/roles_controller.rb
class Users::RolesController < ApplicationController
  def index
    authorize %i[users roles]

    @roles = Role.all
  end

  def new
    authorize %i[users roles]

    @role = Role.new
  end

  def edit
    authorize %i[users roles]

    get_role
  end

  def create
    authorize %i[users roles]

    @role = Role.new(role_params)

    if @role.save
      redirect_to users_roles_url, notice: t('.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize %i[users roles]

    if get_role.update(role_params)
      redirect_to users_roles_url, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize %i[users roles]

    get_role.destroy

    respond_to do |format|
      format.html { redirect_to users_roles_url, notice: t('.destroyed') }
    end
  end

  private

  def get_role
    @role = Role.find(params[:id])
  end

  def role_params
    params.require(:role).permit(:rol_name, :description, permission_ids: [])
  end
end

app/views/users/profiles/index.html.erb
<div class="profile">
  <div class="profile-header">
    <!-- BEGIN profile-header-tab -->
    <ul class="profile-header-tab nav nav-tabs px-3 pb-1 pt-2">
      <li class="nav-item"><a href="#profile-info" class="nav-link active" data-bs-toggle="tab"><%= t '.profile' %></a></li>
      <li class="nav-item"><a href="#profile-medical-file" class="nav-link" data-bs-toggle="tab"><%= t '.medical_file' %></a></li>
    </ul>
    <!-- END profile-header-tab -->

    <!-- BEGIN profile-content -->
    <div class="profile-content">
      <!-- BEGIN tab-content -->
      <div class="tab-content p-0">
        <!-- BEGIN #profile-info tab -->
        <div class="tab-pane fade show active" id="profile-info">
          <!-- BEGIN table -->
          <div class="table-responsive form-inline">
            <table class="table table-profile align-middle">
              <tbody>
                <tr class="highlight">
                  <td class="as_field_custom">Mobile</td>
                  <td><i class="fa fa-mobile fa-lg me-5px"></i> <%= @member&.phone %></td>
                </tr>
                <tr class="divider">
                  <td colspan="2"></td>
                </tr>
                <tr>
                  <td class="as_field_custom">Genero</td>
                  <td><%= @member.gender %></td>
                </tr>
                <tr>
                  <td class="as_field_custom">Fecha de nacimiento</td>
                  <td><%= @member.birthdate %> / <%= @member.age %> Años.</td>
                </tr>
                <tr>
                  <td class="as_field_custom">Fecha de admisión</td>
                  <td><%= @member.date_admission %></td>
                </tr>
                <tr>
                  <td class="as_field_custom">Fecha de promesa</td>
                  <td><%= @member.date_promise %></td>
                </tr>
                <tr>
                  <td class="as_field_custom">Tipo de miembro</td>
                  <td><%= @member.member_type %></td>
                </tr>
                <tr>
                  <td class="as_field_custom">Segundo correo electrónico</td>
                  <td><%= @member.second_email %></td>
                </tr>
                <tr>
                  <td class="as_field_custom">Renovación de estatus</td>
                  <td>
                    <%= "Desactivada" unless @member.status_renewal === "enabled" %>
                    <%= "Activa" if @member.status_renewal === "enabled" %> - <%= current_user.payment_renewal_end %></td>
                </tr>
                <tr class="divider">
                  <td colspan="2"></td>
                </tr>
                <!-- <tr class="highlight">
                  <td class="as_field_custom">&nbsp;</td>
                  <td class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary w-150px">Edit</button>
                  </td>
                </tr> -->
              </tbody>
            </table>
          </div>
          <!-- END table -->
        </div>
        <!-- END #profile-info tab -->
        <!-- BEGIN #profile-medical-file tab -->
        <div class="tab-pane fade" id="profile-medical-file">
          <% unless @member.medical_files.present? %>
            <div class="row mb-2">
              <div class="col">
              </div>
              <div class="col">
                <div class="d-flex justify-content-end">
                  <%= link_to t('.new'), new_users_medical_file_path, class: "btn btn-success btn-sm font-bold" %>
                </div>
              </div>
            </div>
          <% end %>
          <% if @member.medical_files.present? %>
            <% data = @member.medical_files.last %>
            <!-- BEGIN table -->
            <div class="table-responsive form-inline">
              <table class="table table-profile align-middle">
                <tbody>
                  <tr class="highlight" style="background: #FFFFFF;">
                    <td class="as_field_custom"><b>Datos basicos</b></td>
                    <td></td>
                  </tr>
                  <tr class="divider">
                    <td colspan="2"></td>
                  </tr>
                  <tr>
                    <td class="as_field_custom">Tipo de sangre</td>
                    <td><%= data&.blood_type %></td>
                  </tr>
                  <tr>
                    <td class="as_field_custom">Estatura</td>
                    <td><%= data&.height %></td>
                  </tr>
                  <tr>
                    <td class="as_field_custom">Peso</td>
                    <td><%= data&.weight %></td>
                  </tr>
                  <tr class="highlight" style="background: #FFFFFF;">
                    <td class="as_field_custom"><b>Datos de Contacto Emergencia</b></td>
                    <td></td>
                  </tr>
                  <tr class="divider">
                    <td colspan="2"></td>
                  </tr>
                  <tr>
                    <td class="as_field_custom">Nombre</td>
                    <td><%= data&.emergency_first_name %> <%= data&.emergency_last_name %></td>
                  </tr>
                  <tr>
                    <td class="as_field_custom">Telefono</td>
                    <td><%= data&.emergency_number %></td>
                  </tr>
                  <% if @vaccines_member.present? %>
                    <tr class="highlight" style="background: #FFFFFF;">
                      <td class="as_field_custom"><b>Vacunas</b></td>
                      <td></td>
                    </tr>
                    <tr class="divider">
                      <td colspan="2"></td>
                    </tr>
                    <tr>
                      <td class="as_field_custom">
                        <% @vaccines_member.each do |e| %>
                          <span class="mx-3"><%= e.vaccine.vaccine_name %></span>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                  <% if @allergies_member.present? %>
                    <tr class="highlight" style="background: #FFFFFF;">
                      <td class="as_field_custom"><b>Alergias</b></td>
                      <td></td>
                    </tr>
                    <tr class="divider">
                      <td colspan="2"></td>
                    </tr>
                    <tr>
                      <td class="as_field_custom">
                        <% @allergies_member.each do |e| %>
                          <span class="mx-3"><%= e.allergy.allergies_name %></span>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                  <% if @diseases_member.present? %>
                    <tr class="highlight" style="background: #FFFFFF;">
                      <td class="as_field_custom"><b>Antecedentes Psicológicos/Psiquiátricos</b></td>
                      <td></td>
                    </tr>
                    <tr class="divider">
                      <td colspan="2"></td>
                    </tr>
                    <tr>
                      <td class="as_field_custom">
                        <% @diseases_member.each do |e| %>
                          <span class="mx-3"><%= e.disease.diseases_name %></span>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                  <% if @histories_member.present? %>
                    <tr class="highlight" style="background: #FFFFFF;">
                      <td class="as_field_custom"><b>Antecedentes Médicos</b></td>
                      <td></td>
                    </tr>
                    <tr class="divider">
                      <td colspan="2"></td>
                    </tr>
                    <tr>
                      <td class="as_field_custom">
                        <% @histories_member.each do |e| %>
                          <span class="mx-3"><%= e.history.histories_name %></span>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                  <% if @handicaps_member.present? %>
                    <tr class="highlight" style="background: #FFFFFF;">
                      <td class="as_field_custom"><b>Discapacidades</b></td>
                      <td></td>
                    </tr>
                    <tr class="divider">
                      <td colspan="2"></td>
                    </tr>
                    <tr>
                      <td class="as_field_custom">
                        <% @handicaps_member.each do |e| %>
                          <span class="mx-3"><%= e.handicap.handicaps_name %></span>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                  <% if @intolerances_member.present? %>
                    <tr class="highlight" style="background: #FFFFFF;">
                      <td class="as_field_custom"><b>Intolerancias</b></td>
                      <td></td>
                    </tr>
                    <tr class="divider">
                      <td colspan="2"></td>
                    </tr>
                    <tr>
                      <td class="as_field_custom">
                        <% @intolerances_member.each do |e| %>
                          <span class="mx-3"><%= e.intolerance.intolerances_name %></span>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                  <tr class="highlight">
                    <td class="as_field_custom">&nbsp;</td>
                    <td class="d-flex justify-content-end">
                      <%= link_to t('.edit'), edit_users_medical_file_path(@medical_files.id), class: "btn btn-primary btn-sm font-bold" %>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <!-- END table -->
          <% end %>
        </div>
        <!-- END #profile-medical-file tab -->
      </div>
      <!-- END tab-content -->
    </div>
    <!-- END profile-content -->
  </div>
</div>