config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :home do
        collection do
          post :search
        end
      end
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    authenticated :user do
      root to: 'pages#index', as: :authenticated_root
      get '/users/sign_out', to: 'devise/sessions#destroy'

      resources :members, only: %i[index new create edit update] do
        collection do
          get :regions
          get :districts
          get :groups
          get :units
          get :advance
          get :states
          get :provinces
          post :verificate
        end
      end

      get '/members/grupo'
      get '/members/group_youth'
      get '/members/dualidad'
      get '/members/institucional'
      get '/members/legal_tutor'
      post '/members/grupo_submit'
      post '/members/group_youth_submit'
      post '/members/dualidad_submit'
      post '/members/institucional_submit'
      post '/members/legal_tutor_submit'
      post '/members/verificate'

      namespace :users do
        resources :amounts
        resources :profiles, only: %i[index]
        resources :resets, only: %i[update] do
          collection do
            get :group
            get :district
            get :region
          end
        end
        resources :reports do
          collection do
            get :payments
            get :members
            get :tutors_legals
            get :numerical_cutoff
            get :my_group
            get :my_district
            get :my_region
            get :reports_by_payments, format: :xlsx
            get :reports_by_members, format: :xlsx
            get :reports_by_tutors_legals, format: :xlsx
            get :reports_by_numerical_cutoff, format: :xlsx
            get :reports_by_my_group, format: :xlsx
            get :reports_by_my_district, format: :xlsx
            get :reports_by_my_region, format: :xlsx
          end
        end
        resources :payments, only: %i[index new create show destroy] do
          collection do
            get :checkings
            post :swap
          end
        end
        resources :roles, except: [:show]
        resources :vaccines, except: [:show]
        resources :allergies, excep: [:show]
        resources :diseases, excep: [:show]
        resources :histories, excep: [:show]
        resources :handicaps, excep: [:show]
        resources :intolerances, excep: [:show]
        resources :medical_files, only: %i[new edit create update]
        resources :assignments, only: %i[index] do
          collection do
            post :assignment
          end
        end
      end
    end

    unauthenticated :user do
      root to: 'users/sessions#new', as: :unauthenticated_root
    end

    get 'static_pages/no_permissions', to: 'static_pages#no_permissions', as: 'static_pages_no_permissions'
  end
end

app/views/shared/_begin_profile.html.erb
<!-- BEGIN profile -->
<div class="profile">
  <div class="profile-header">
    <!-- BEGIN profile-header-cover -->
    <div class="profile-header-cover"></div>
    <!-- END profile-header-cover -->
    <!-- BEGIN profile-header-content -->
    <div class="profile-header-content">
      <!-- BEGIN profile-header-info -->
      <div class="profile-header-info">
        <h4 class="mt-0 mb-1">Unidad <%= current_user.member&.group_unit&.unit&.unit_name %></h4>
        <p class="mb-1">Grupo <%= current_user.member&.group_unit&.group&.group_name %> / Distrito <%= current_user.member&.group_unit&.group&.district&.district_name %> / Region <%= current_user.member&.group_unit&.group&.district&.region&.region_name %></p>
        <p class="mb-1">Valido <%= current_user.payment_renewal_end %></p>
      </div>
      <!-- END profile-header-info -->
    </div>
    <!-- END profile-header-content -->
  </div>
</div>
<!-- END profile -->

app/views/shared/_flash.html.erb
<p class="notice"><%= notice if notice %></p>
<p class="alert"><%= alert if alert %></p>

app/views/shared/_header.html.erb
<!-- BEGIN #header -->
<div id="header" class="app-header">
  <!-- BEGIN navbar-header -->
  <div class="navbar-header">
    <%= link_to authenticated_root_path, class: "navbar-brand" do %>
      <span class="navbar-logo"></span>
      <span><b class="me-3px">Scouts</b> Venezuela</span>
    <% end %>
    <button type="button" class="navbar-mobile-toggler" data-toggle="app-sidebar-mobile">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <!-- END navbar-header -->
  <!-- BEGIN header-nav -->
  <div class="navbar-nav">
    <div class="navbar-item navbar-user dropdown">
      <a href="#" class="navbar-link dropdown-toggle d-flex align-items-center" data-bs-toggle="dropdown">
        <%= image_tag('user-13.jpg') %>
        <span>
          <span class="d-none d-md-inline"><%= current_user.full_name %></span>
          <b class="caret"></b>
        </span>
      </a>
      <div class="dropdown-menu dropdown-menu-end me-1">
        <%= link_to(users_profiles_path, class: "#{'active' if current_page?(users_profiles_path)} dropdown-item") do %>
          <span><%= t('.users_profiles') %></span>
        <% end %>
        <%= link_to destroy_user_session_path, data: {
          turbo_method: :delete,
          turbo_confirm: (t '.confirmation')
        }, class: "dropdown-item" do %>
          <span><%= t '.log_out' %></span>
        <% end %>
      </div>
    </div>
  </div>
  <!-- END header-nav -->
</div>
<!-- END #header -->

app/views/shared/_nav_not_completeness.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to members_path, class: "navbar-brand" do %>
      <span>Inicio</span>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        </li>
      </ul>
      <div class="d-flex">
        <%= link_to destroy_user_session_path, data: {
          turbo_method: :delete,
          turbo_confirm: 'Confirmar'
        }, class: "btn btn-outline-success" do %>
          <span>Cerrar sesión</span>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_toast.html.erb
<% if alert || notice %>
  <div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
    <div id="liveToast" class="toast fase show" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <strong class="me-auto">ASVenezuela</strong>
        <small>Notificación</small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body">
        <%= alert || notice %>
      </div>
    </div>
  </div>
<% end %>